permalink: /:year/:month/:day/:title.html
paginate: 10
markdown: kramdown

kramdown:
  input: GFM

# 作者信息
author: 
  name: cylong
  email: cuiyulong2011@gmail.com
  link: http://cylong.me
  weibo: http://weibo.com/304503136
  github: http://github.com/CyL0NG

# 站点信息
title: CyL0NG的博客 
description: CyL0NG的博客
url: http://cylong.me
rss_url: /pages/atom.xml

# gavatar头像及Favicon
gavatar: /public/img/gavatar.png
favicon: /public/img/favicon.ico

# google analytics 设置

# disqus 设置
disqus:
  shortname: cylong

# 主题设置，自动激活某个标签
active: 技术

# 首页除了最新文章外显示分类
cates: 
  - Python
  - Infosec

# 中文本地化
locals:
  tags: 标签
  about: 关于
  newest: 最新文章
  archive: 归档
  content: 目录
